apiVersion: "2015-06-15"

virtualNetworkName: "KubVNET"

subnetAdminName: "ad-subnet"
subnetMastersName: "master-subnet"
subnetMinionsName: "minion-subnet"

routeTableName: "routetable"
securityGroupName: "secgroup"

nameSuffix: "{{cluster_name}}"

availabilitySetMasters: "master-avs"
availabilitySetMinions: "minion-avs"

faultDomainCount: 3
updateDomainCount: 10

bastionVmSize: Standard_A0
bastionVMName: bastion
bastionIPAddressName: bastion-pubip

mastersVmSize: Standard_A2
mastersOsDiskSize: 1000
mastersCount: "{{masters_count}}"

minionsVmSize: Standard_A2
minionsOsDiskSize: 1000
minionsCount: "{{minions_count}}"


adminUserName: devops
adminPassword: "{{azure_admin_password}}"
disablePasswordAuthentication: true

sshKeyPath: "/home/{{adminUserName}}/.ssh/authorized_keys"
sshKeyData: "{{azure_ssh_pubkey}}"

imageReference:
  publisher: "OpenLogic"
  offer: "CentOS"
  sku: "7.2"
  version: "latest"
imageReferenceJson: "{{imageReference|to_json}}"

storageAccountName: "sa{{cluster_name | replace('-', '')}}"
storageAccountType: "Standard_LRS"

