---
- set_fact:
    kubelet_args_cloud_provider: ""
    kubelet_args_register_schedulable: ""

- set_fact:
    kubelet_args_cloud_provider: "--cloud-provider=azure --cloud-config=/etc/kubernetes/cloud-config.json"

- set_fact:
    kubelet_args_dns: "--cluster-dns={{cluster_dns}} --cluster-domain=cluster.local"

#- set_fact:
#    kubelet_args_network: "--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"
#  when: inventory_hostname in groups['role_master']

- set_fact:
    kubelet_args_network: "--hairpin-mode=promiscuous-bridge --network-plugin=kubenet --reconcile-cidr"
#  when: inventory_hostname in groups['role_minion']

#- set_fact:
#    kubelet_args_register_schedulable: "--register-schedulable=false"
#  when: inventory_hostname in groups['role_master']

- name: install args dropin for kubelet
  template: src=20-kubeadm-extra-args.conf dest=/etc/systemd/system/kubelet.service.d/20-kubeadm-extra-args.conf owner=root group=root mode=0644
  register: s

- name: systemctl daemon reload
  command: systemctl daemon-reload
  when: s.changed

- name: restart kubelet
  service: name=kubelet state=restarted
  when: s.changed