---
elrepo_rpm : elrepo-release-7.0-2.el7.elrepo.noarch.rpm
elrepo_mirror : http://www.elrepo.org
elrepo_timeout_seconds : 600

elrepo_url : '{{elrepo_mirror}}/{{elrepo_rpm}}'

elrepo_kernel_package: kernel-ml-4.8.11