apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: kube-registry-proxy
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        k8s-app: kube-registry-proxy
    spec:
      containers:
      - name: kube-registry-proxy
        image: gcr.io/google_containers/kube-registry-proxy:0.3
        resources:
          limits:
            cpu: 100m
            memory: 50Mi
        env:
        - name: REGISTRY_HOST
          value: kube-registry.kube-system.svc.cluster.local
        - name: REGISTRY_PORT
          value: "5000"
        - name: FORWARD_PORT
          value: "{{cluster_registry_nodeport}}"
        ports:
        - name: registry
          containerPort: {{cluster_registry_nodeport}}
          hostPort: {{cluster_registry_nodeport}}
