apiVersion: v1
kind: Service
metadata:
  name: traefik-ingress-controller
  namespace: kube-system
  labels:
    k8s-app: traefik-ingress-controller
    #kubernetes.io/cluster-service: "true"
    #kubernetes.io/name: "TraefikIngressControllerService"
spec:
  type: LoadBalancer
  selector:
    k8s-app: traefik-ingress-controller
  ports:
  - name: http
    port: 80
    protocol: TCP
  - name: https
    port: 443
    protocol: TCP
