---
- name: check if docker data partition already exists
  stat: path="{{device}}1"
  register: s

- name: create docker data partition
  shell: echo -e "o\nn\np\n1\n\n\nw" | fdisk {{device}}
  when: not s.stat.exists

- name: format docker data partition
  shell: "mkfs.{{fs_type}} {{device}}1"
  when: not s.stat.exists

- name: create systemd mount for docker data partition
  template: src=var-lib-docker.mount dest=/etc/systemd/system/var-lib-docker.mount
  register: t1

- name: make sure /etc/systemd/system/docker.service.d exists
  file: path=/etc/systemd/system/docker.service.d state=directory

- name: add docker dropin for mount dependency
  template: src=01-var-lib-docker.conf dest=/etc/systemd/system/docker.service.d/01-var-lib-docker.conf
  register: t2

- name: systemctl daemon-reload
  command: systemctl daemon-reload
  when: "t1.changed or t2.changed"