---
- name: install ELRepo key
  rpm_key: state=present key='https://www.elrepo.org/RPM-GPG-KEY-elrepo.org'

- name: get rpm...
  get_url: >-
    url={{elrepo_url}}
    dest=/tmp/{{elrepo_rpm}}
    owner=root
    group=root
    mode=0644
    timeout={{elrepo_timeout_seconds}}

- name: install ELRepo
  become: yes
  become_user: root
  package: state=present name=/tmp/{{elrepo_rpm}}

- name: upgrade kernel
  yum: name={{elrepo_kernel_package}} state=latest enablerepo=elrepo-kernel
  register: upgrade

- name: changed default grub entry
  lineinfile:
    dest: '/etc/default/grub'
    regexp: '^GRUB_DEFAULT=.*'
    line: 'GRUB_DEFAULT=0'
  when: upgrade.changed
  register: grub_entry

- name: re-generate grub-config
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: upgrade.changed and grub_entry.changed

- name: Rebooting ...
  shell: sleep 2 && shutdown -r now "Reboot required for updated kernel"
  async: 0
  poll: 0
  sudo: true
  ignore_errors: true
  when: upgrade.changed

- name: waiting for server to come back
  local_action: wait_for host={{ inventory_hostname }} state=started
  become: false
  when: upgrade.changed
