---
- name: check if traefik-ingress-controller is installed
  command: kubectl --namespace kube-system describe deploy traefik-ingress-controller
  register: check
  changed_when: False
  failed_when: False

- file: path=/home/devops/addons/traefik-ingress-controller state=directory
  become: no

- name: traefik-ingress-controller templates
  become: no
  template: src="traefik-ingress-controller/{{ item }}" dest="/home/devops/addons/traefik-ingress-controller/{{ item }}"
  with_items:
    - traefik-ingress-controller.yaml
    - traefik-ingress-controller-svc.yaml
    - traefik-ingress-controller-admin-svc.yaml
  register: templates

- name: install traefik-ingress-controller
  command: kubectl apply -f "/home/devops/addons/traefik-ingress-controller/{{ item.item }}"
  when: check.rc != 0 or item.changed
  with_items: '{{templates.results}}'
